#set -s escape-time 0

unbind C-b
set-option -g prefix M-Space
#bind-key C-a send-prefix

bind -r ^ last-window
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

# bind -r 1 select-window -t:=0
# bind -r 2 select-window -t:=1
# bind -r 3 select-window -t:=2
# bind -r 4 select-window -t:=3
# bind -r 5 select-window -t:=4
# bind -r 6 select-window -t:=5
# bind -r 7 select-window -t:=6
# bind -r 8 select-window -t:=7
# bind -r 9 select-window -t:=8
# bind -r 0 select-window -t:=9

set -g base-index 1
set -g pane-base-index 1

set -g status-style 'bg=#333333 fg=#5eacd3'
