# https://github.com/christoph-heinrich/mpv-quality-menu
g-V   script-binding quality_menu/video_formats_toggle
g-A   script-binding quality_menu/audio_formats_toggle
Ctrl+r script-binding quality_menu/reload
